spring:
   application:
      name: netflix-eureka-client-one-hystrix

server:
   port: 8081

eureka:
   instance:
      leaseRenewalIntervalInSeconds: 1
      leaseExpirationDurationInSeconds: 2
   client:
      initialInstanceInfoReplicationIntervalSeconds: 0
      instanceInfoReplicationIntervalSeconds: 1
      registryFetchIntervalSeconds: 1
      serviceUrl:
         defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
      healthcheck:
         enabled: true