spring:
   application:
      name: netflix-eureka-two

server:
   port: 8082

eureka:
   instance:
      leaseRenewalIntervalInSeconds: 1
      leaseExpirationDurationInSeconds: 2
   client:
      initialInstanceInfoReplicationIntervalSeconds: 0
      instanceInfoReplicationIntervalSeconds: 1
      registryFetchIntervalSeconds: 1
      serviceUrl:
         defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
      healthcheck:
         enabled: true